insert into kategzvi (NZVIRKAT,CNAZEVKAT,NPOHLAVI,CNAZPOL2,NUCETSKUP,CUCETSKUP,CDANPZBO,CTYPSKP,NCENAV1ZV,NCENAV2ZV,LVZRUST,    
                      NZVIRKATPR,CNAZPOL2PR,NTYPVYPCEL,CTYPEVID,CTYPVYPCEN,NODPISKD,CODPISKD,NTYPDODPI,NODPISK,CODPISK,    
                       NTYPUODPI,NTYPVYPUO,NROKYODPIU,NUPLPROC,NUCETSKUPP,NKCPREVTOP,NKCPREVBOT,NZPUODPIS,NZNAKT,NZNAKTD)

   select  NZVIRKAT,CNAZEVKAT,NPOHLAVI,CNAZPOL2,NUCETSKUP,CUCETSKUP,CDANPZBO,CTYPSKP,NCENAV1ZV,NCENAV2ZV,LVZRUST,    
                      NZVIRKATPR,CNAZPOL2PR,NTYPVYPCEL,CTYPEVID,CTYPVYPCEN,NODPISKD,CODPISKD,NTYPDODPI,NODPISK,CODPISK,    
                       NTYPUODPI,NTYPVYPUO,NROKYODPIU,NUPLPROC,NUCETSKUPP,NKCPREVTOP,NKCPREVBOT,NZPUODPIS,NZNAKT,NZNAKTD
   from kategzvi_
