update autom_hd set  
cNAKLUc_NV = mNAKLUc_NV,
cPRODUc_NV = mPRODUc_NV,
cUCTYUc_NV = mUCTYUc_NV,
cREZIUc_VR = mREZIUc_VR,
cNAKLUc_VR = mNAKLUc_VR,
cVYNOUc_VR = mVYNOUc_VR,
cZAKLUc_VR = mZAKLUc_VR,
cROZPUc_VR = mROZPUc_VR,
cREZIUc_SR = mREZIUc_SR,
cNAKLUc_SR = mNAKLUc_SR,
cVYNOUc_SR = mVYNOUc_SR,
cZAKLUc_SR = mZAKLUc_SR,
cROZPUc_SR = mROZPUc_SR,
cNAKLUc_ZR = mNAKLUc_ZR,
cVYNOUc_ZR = mVYNOUc_ZR,
cZAKLUc_ZR = mZAKLUc_ZR,
cROZPUc_ZR = mROZPUc_ZR


