(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function h(a,b){a=a.split(".");var c=g;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function k(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.h=function(d,f,e){for(var F=Array(arguments.length-2),u=2;u<arguments.length;u++)F[u-2]=arguments[u];return b.prototype[f].apply(d,F)}};function l(){}var m="function"==typeof Uint8Array;function n(a,b,c){a.c=null;b||(b=[]);a.j=void 0;a.f=-1;a.a=b;a:{if(b=a.a.length){--b;var d=a.a[b];if(!(null===d||"object"!=typeof d||Array.isArray(d)||m&&d instanceof Uint8Array)){a.g=b-a.f;a.b=d;break a}}a.g=Number.MAX_VALUE}a.i={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.g?(d+=a.f,a.a[d]=a.a[d]||p):(q(a),a.b[d]=a.b[d]||p)}var p=[];function q(a){var b=a.g+a.f;a.a[b]||(a.b=a.a[b]={})}
function r(a,b){if(b<a.g){b+=a.f;var c=a.a[b];return c===p?a.a[b]=[]:c}if(a.b)return c=a.b[b],c===p?a.b[b]=[]:c}function t(a,b){a=r(a,b);return null==a?a:!!a}function v(a){a=r(a,3);return null==a?0:a}function w(a,b){a=t(a,b);return null==a?!1:a}function x(a,b,c){b<a.g?a.a[b+a.f]=c:(q(a),a.b[b]=c)}function y(a,b,c,d){c!==d?x(a,b,c):b<a.g?a.a[b+a.f]=null:(q(a),delete a.b[b]);return a}function z(a,b,c){a.c||(a.c={});if(!a.c[c]){var d=r(a,c);d&&(a.c[c]=new b(d))}return a.c[c]}
function A(a,b,c){a.c||(a.c={});var d=c?c.a:c;a.c[b]=c;x(a,b,d)}function B(a,b){return new a(b?JSON.parse(b):null)}l.prototype.toString=function(){return this.a.toString()};function C(a){n(this,a,D)}k(C,l);var D=[17];function E(a){n(this,a,G)}k(E,l);var G=[8];function H(a){n(this,a,I)}k(H,l);var I=[27];function J(a){n(this,a,K)}k(J,l);var K=[1,2,3];function L(a){n(this,a,null)}k(L,l);function M(a){n(this,a,null)}k(M,l);function N(a){n(this,a,aa)}k(N,l);var aa=[13];function O(a){n(this,a,ba)}k(O,l);var ba=[8];function P(a){n(this,a,ca)}k(P,l);var ca=[12];function Q(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function R(a,b){b=new CustomEvent(b);a.a.dispatchEvent(b)}
class da{constructor(a){this.a=a;var b=Q(a,"namespace");if(!b){b="ns-"+Math.random().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");a.setAttribute("name",
"namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}}};function S(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function T(a){if(1>=a.b.offsetWidth||1>=a.b.offsetHeight)return!1;a.a.remove();R(a.c,"spanReady");return!0}
class ea{constructor(a,b){this.c=a;this.f=b;this.b=S("SPAN");this.b.style.fontSize="6px";this.b.textContent="go";this.a=S("DIV");this.a.style.position="absolute";this.a.style.top="100%";this.a.style.left="100%";this.a.style.width="1px";this.a.style.height="0";this.a.style.overflow="hidden";this.a.style.visibility="hidden";this.a.appendChild(this.b)}wait(){if(w(this.f,1))return null;R(this.c,"spanStart");this.c.a.appendChild(this.a);return T(this)?null:new Promise(a=>{const b=setInterval(()=>{T(this)&&
(clearInterval(b),a())},v(this.f))})}};function U(a){a.b&=-31}function V(a,b){a.b|=b}class fa{constructor(a,b){this.a=a;this.c=b;new P;this.b=0}f(){}};function W(a,b,c){if(b&&c){const d=z(a.a.c,N,6);y(d,2,b,0);y(d,3,c,0)}B(J,Q(a.b.a,"engine_msg")||"[]");return a.a.f()||Promise.resolve()}function ha(a){U(a.a);V(a.a,1);window.AFMA_Communicator&&window.AFMA_Communicator.addEventListener("onshow",()=>{V(a.a,32)});let b=0;const c=a.b.a;c.addEventListener("browserRender",()=>{++b;if(1==b)R(a.b,"overallStart"),W(a).then(()=>{R(a.b,"overallQuiet")});else{var d=c.clientWidth,f=c.clientHeight;d&&f&&W(a,d,f)}})}
class ia{constructor(a,b,c){this.b=new da(a);a=new O(b);this.a=c(this.b,a)}};function ja(a){a.c.length=0;a.b=!0}function X(a,b=null){a.a=!0;const c=()=>{a.b=!1;const d=a.c.shift();return void 0===d?(a.a=!1,Promise.resolve()):X(a,d())};return b?b.then(c,()=>{if(a.b)return c();a.a=!1;return Promise.reject()}):c()}function ka(a,b){for(const c of b)a.c.push(c);return a.a?null:X(a)}class la{constructor(){this.b=this.a=!1;this.c=[]}};var Y={};var ma=class{},Z=class extends ma{constructor(a){super();if(Y!==Y)throw Error("Bad secret");this.a=a}toString(){return this.a}};new Z("about:blank");new Z("about:invalid#zTSz");class na extends fa{constructor(a,b){super(a,b);this.g=new la}f(){ja(this.g);return ka(this.g,[()=>null,()=>{{var a=null;const b=z(z(this.c,N,6),M,1);b&&(a=(new ea(this.a,b)).wait());R(this.a,"browserStart");R(this.a,"browserStartEnd");U(this);V(this,2)}return a},()=>{R(this.a,"browserReady");R(this.a,"browserReadyEnd");V(this,4);R(this.a,"overallReady");return null},()=>{R(this.a,"browserQuiet");R(this.a,"browserQuietEnd");V(this,8);return null}])}}
(function(a){let b=null;h("mys.engine.init",(c,d)=>{c=B(O,Q(d,"render_config")||"[]");b=new ia(d,c.a,a);ha(b)});h("mys.engine.stage",()=>b?b.a.b:0)})(function(a,b){if(null!=r(b,6))var c=z(b,N,6);else{c=z(b,H,1);var d=z(b,E,12)||new E;var f=new N;var e=t(d,6)||!1;f=y(f,10,e,!1);e=r(d,2)||0;f=y(f,7,e,0);e=t(d,15)||!1;f=y(f,18,e,!1);e=t(d,17)||!1;f=y(f,20,e,!1);e=r(c,42);e=null==e?e:+e;f=y(f,21,(null==e?0:e)||1,0);e=new M;e=y(e,3,100,0);e=y(e,4,1E4,0);t(d,4)?(y(e,6,!0,!1),y(e,7,"monospace",""),y(e,8,
"IMWimw0.!?@","")):(t(d,5)&&y(e,9,!0,!1),y(e,5,!0,!1));A(f,1,e);e=new L;z(c,C,10)&&w(z(c,C,10),6)&&y(e,1,!0,!1);w(c,16)&&!t(d,1)&&y(e,2,!0,!1);A(f,4,e);c=f}A(b,6,c);return new na(a,b)});}).call(this);
