INSERT INTO OBJITEM(
nDoklad,nextObj,nCisFirmy,cCinnost,cCislObINT,nCislPolOb,cNazZBO,nKlicNaz,cSklPol,cPolCen,nZboziKAT,nKlicDpH,NPREDANPOV,
cCislVpINT,dDatVpINT,lViceVpINT,nMnozVpINT,nCenaPrINT,cCisSklad,cCislObDOD,ndokladNav,nCisOdes,cNazOdes,ncountNav,dDatObDOD, 
nMnozObDOD,nMnozPoDOD,dDatPoDOD,nMnozKoDod,nCenNaoDOD,nCenProDOD,dDatPrDOD,nCenNapDOD,nMnozPrDOD,nMnozObODB,nMnozPoODB,nMnozPdODB,
cMnozPoODB,nMnozNeODB,dDatReODB,dDatDoOdb,nMnozReODB,nMnozPlODB,nKcsBdObj,nKcsZdObj,nCenaDlODB,nIntIndOBJ,cCisZakaz,cCisZakazI,
nCislPolZa,cZkratJedn,nTypSlevy,nProcSlev,nPROCslFAO,lPROCslFAO,nPROCslHOT,nPROCslMNO,nHodnSlev,nCenaZakl,nCelkSlev,nKlicObl,  
cZkrProdej,nPodilProd,nMnPotVyr,nMnPusVyr,dPusVyr,nMnPriVyr,dPriVyr,cVyrPol,nVarCis,cStred,nRAvyska,nRBsirka,
lPozVyroba,nMnKalkul,nDelka,nPocet,nPozice,nMnNaKus,cText1,cText2,nRokRV,nPolObjRV,dDATodvVYR,cPOPpolOBJ,nUCETskup,aULOZENI,
dRezerv,cRezerv,nNavysPRC,nKusRoz,nCisOper,nPocCeZapZ,cKodPoz,ccistrasyp,ccistrasys,nCisDodavk,NMNOZSZBO,NMNOZKZBO,NMNOZOZBO,
NMNOZRZBO,NMNOZDZBO,nCisVysFak,cDoplnTxt,nMnoz_FAKT,nstav_FAKT,nMnoz_DLVY,nMnoz_OBJP,nMnoz_EXPL,nMnoz_ZAK,ddatRvykr,NHMOTNOSTJ,
NOBJEMJ,NHMOTNOST,NOBJEM,nMnoz_NABV,nStav_NABV,nMnoz_FAKV,nStav_FAKV,nMnoz_DLV,nStav_DLV,nMnoz_OBJP,nStav_OBJP,nMnoz_EXLV,nStav_EXLV,
nMnoz_VYRZ,nStav_VYRZ,nMnoz_KSMV,nStav_KSMV,nMnoz_SVYD,nStav_SVYD,nMnozZdok,dVznikZazn,dZmenaZazn,mPoznamka, mUserZmenR)
SELECT
nDoklad,nextObj,nCisFirmy,cCinnost,cCislObINT,nCislPolOb,cNazZBO,nKlicNaz,cSklPol,cPolCen,nZboziKAT,nKlicDpH,NPREDANPOV,
cCislVpINT,dDatVpINT,lViceVpINT,nMnozVpINT,nCenaPrINT,cCisSklad,cCislObDOD,ndokladNav,nCisOdes,cNazOdes,ncountNav,dDatObDOD, 
nMnozObDOD,nMnozPoDOD,dDatPoDOD,nMnozKoDod,nCenNaoDOD,nCenProDOD,dDatPrDOD,nCenNapDOD,nMnozPrDOD,nMnozObODB,nMnozPoODB,nMnozPdODB,
cMnozPoODB,nMnozNeODB,dDatReODB,dDatDoOdb,nMnozReODB,nMnozPlODB,nKcsBdObj,nKcsZdObj,nCenaDlODB,nIntIndOBJ,cCisZakaz,cCisZakazI,
nCislPolZa,cZkratJedn,nTypSlevy,nProcSlev,nPROCslFAO,lPROCslFAO,nPROCslHOT,nPROCslMNO,nHodnSlev,nCenaZakl,nCelkSlev,nKlicObl,  
cZkrProdej,nPodilProd,nMnPotVyr,nMnPusVyr,dPusVyr,nMnPriVyr,dPriVyr,cVyrPol,nVarCis,cStred,nRAvyska,nRBsirka,
lPozVyroba,nMnKalkul,nDelka,nPocet,nPozice,nMnNaKus,cText1,cText2,nRokRV,nPolObjRV,dDATodvVYR,cPOPpolOBJ,nUCETskup,aULOZENI,
dRezerv,cRezerv,nNavysPRC,nKusRoz,nCisOper,nPocCeZapZ,cKodPoz,ccistrasyp,ccistrasys,nCisDodavk,NMNOZSZBO,NMNOZKZBO,NMNOZOZBO,
NMNOZRZBO,NMNOZDZBO,nCisVysFak,cDoplnTxt,nMnoz_FAKT,nstav_FAKT,nMnoz_DLVY,nMnoz_OBJP,nMnoz_EXPL,nMnoz_ZAK,ddatRvykr,NHMOTNOSTJ,
NOBJEMJ,NHMOTNOST,NOBJEM,nMnoz_NABV,nStav_NABV,nMnoz_FAKV,nStav_FAKV,nMnoz_DLV,nStav_DLV,nMnoz_OBJP,nStav_OBJP,nMnoz_EXLV,nStav_EXLV,
nMnoz_VYRZ,nStav_VYRZ,nMnoz_KSMV,nStav_KSMV,nMnoz_SVYD,nStav_SVYD,nMnozZdok,dVznikZazn,dZmenaZazn,mPoznamka, mUserZmenR
FROM OBJITEM_
