INSERT INTO ZMAJUZ 
(CULOHA,CTYPDOKLAD,CTYPPOHYBU,CDENIK,NDOKLAD,NORDITEM,NINVCIS,CNAZEV,NUCETSKUP,CUCETSKUP,NDRPOHYB,NKARTA,NTYPPOHYB,DDATZMENY,COBDOBI,NROK,NOBDOBI,
NPORZMENY,NCISLODL,NCISFAK,CVARSYM,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NOPRUCT,NZUSTCENAU,NUCTODPMES,NZMENVSTCU,NZMENOPRU,NZMENVSTCD,NZMENOPRD,
CUSERABB,CNAZPOL1,CNAZPOL2,CNAZPOL3,CNAZPOL4,CNAZPOL5,CNAZPOL6,NCENAPORUO,NCENAPORDO,NDOTACEUO,NDOTACEDO,NCENAVSTUO,NCENAVSTDO,NOPRUCTO,
NOPRDANO,NPROCDANOO,NDANODPRO,NPROCUCTOO,NUCTODPRO,NUCTODPMO,NZNAKTO,NZNAKTDO,COBDZVYSO,NLIKCELDOK,CNAZPOL1_N,CNAZPOL4_N,NZVIRKAT_N,NDOKL183,
NCENAPORUN,NCENAPORDN,NDOTACEUN,NDOTACEDN,NCENAVSTUN,NCENAVSTDN,NOPRUCTN,NOPRDANN,NPROCDANON,NDANODPRN,NPROCUCTON,NUCTODPRN,NUCTODPMN,NZNAKTN,
NZNAKTDN,COBDZVYSN,nKLikvid,nZLikvid,dVznikZazn,dZmenaZazn)
SELECT 
CULOHA,CTYPDOKLAD,CTYPPOHYBU,CDENIK,NDOKLAD,NORDITEM,NINVCIS,CNAZEV,NUCETSKUP,CUCETSKUP,NDRPOHYB,NKARTA,NTYPPOHYB,DDATZMENY,COBDOBI,NROK,NOBDOBI,
NPORZMENY,NCISLODL,NCISFAK,CVARSYM,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NOPRUCT,NZUSTCENAU,NUCTODPMES,NZMENVSTCU,NZMENOPRU,NZMENVSTCD,NZMENOPRD,
CUSERABB,CNAZPOL1,CNAZPOL2,CNAZPOL3,CNAZPOL4,CNAZPOL5,CNAZPOL6,NCENAPORUO,NCENAPORDO,NDOTACEUO,NDOTACEDO,NCENAVSTUO,NCENAVSTDO,NOPRUCTO,
NOPRDANO,NPROCDANOO,NDANODPRO,NPROCUCTOO,NUCTODPRO,NUCTODPMO,NZNAKTO,NZNAKTDO,COBDZVYSO,NLIKCELDOK,CNAZPOL1_N,CNAZPOL4_N,NZVIRKAT_N,NDOKL183,
NCENAPORUN,NCENAPORDN,NDOTACEUN,NDOTACEDN,NCENAVSTUN,NCENAVSTDN,NOPRUCTN,NOPRDANN,NPROCDANON,NDANODPRN,NPROCUCTON,NUCTODPRN,NUCTODPMN,NZNAKTN,
NZNAKTDN,COBDZVYSN,nKLikvid,nZLikvid,dVznikZazn,dZmenaZazn
FROM ZMAJUZ_  
