INSERT INTO MAJZ 
(NINVCIS,NZVIRKAT,LHMOTNYIM,NUCETSKUP,CUCETSKUP,CTYPSKP,NODPISKD,CODPISKD,NTYPDODPI,NROKYODPID,NMESODPID,NODPISK,CODPISK,NTYPUODPI,NROKYODPIU,
NMESODPIUZ,NTYPVYPUO,CNAZEV,NTROBOR,NZNAKT,NZNAKTD,NDOKLAD,NDRPOHYB,CTYPPOHYBU,DDATPOR,DDATZAR,COBDZAR,DDATVYRAZ,COBDVYRAZ,DDATZVYS,COBDZVYS,
NROKYDANOD,NROKZVDANO,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NCENAVSTD,NOPRUCT,NOPRDAN,NOPRUCTPS,NOPRDANPS,NDOTACEUCT,NDOTACEDAN,NCENAPORU,
NCENAPORD,NPROCDANOD,NDANODPROK,NPROCUCTOD,NUCTODPROK,NUCTODPMES,NPOCMESUO,NPOCMESDO,NUPLPROC,NUPLHODN,NROKUPL,CKLICODMIS,COBDPOSODP,
CNAZPOL1,CNAZPOL2,CNAZPOL3,CNAZPOL4,CNAZPOL5,CNAZPOL6,MPOPIS,NDOKLPREV,CVARSYM,NCISFAK,NZPUODPIS,dVznikZazn,dZmenaZazn)
SELECT 
NINVCIS,NZVIRKAT,LHMOTNYIM,NUCETSKUP,CUCETSKUP,CTYPSKP,NODPISKD,CODPISKD,NTYPDODPI,NROKYODPID,NMESODPID,NODPISK,CODPISK,NTYPUODPI,NROKYODPIU,
NMESODPIUZ,NTYPVYPUO,CNAZEV,NTROBOR,NZNAKT,NZNAKTD,NDOKLAD,NDRPOHYB,CTYPPOHYBU,DDATPOR,DDATZAR,COBDZAR,DDATVYRAZ,COBDVYRAZ,DDATZVYS,COBDZVYS,
NROKYDANOD,NROKZVDANO,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NCENAVSTD,NOPRUCT,NOPRDAN,NOPRUCTPS,NOPRDANPS,NDOTACEUCT,NDOTACEDAN,NCENAPORU,
NCENAPORD,NPROCDANOD,NDANODPROK,NPROCUCTOD,NUCTODPROK,NUCTODPMES,NPOCMESUO,NPOCMESDO,NUPLPROC,NUPLHODN,NROKUPL,CKLICODMIS,COBDPOSODP,
CNAZPOL1,CNAZPOL2,CNAZPOL3,CNAZPOL4,CNAZPOL5,CNAZPOL6,MPOPIS,NDOKLPREV,CVARSYM,NCISFAK,NZPUODPIS,dVznikZazn,dZmenaZazn
FROM MAJZ_  
