INSERT INTO zvkarty (CTYPEVID,CNAZPOL1,CNAZPOL4,NZVIRKAT,CNAZPOL2,CNAZEV,NUCETSKUP,CUCETSKUP,CDANPZBO,CTYPSKP,DDATPORKAR,
                     CZKRATJEDN,NKLICDPH,CTYPVYPCEN,CZKRATMENY,NCENANZV,NCENCNZV,NCENAV1ZV,NCENAV2ZV,NCENASZV,NCENACZV,
                     NCENAPZV,NCENAMZV,NMNOZSZV,NKUSYZV,NKD,NCENAPOCZV,NMNOZPOCZV,NKUSYPOCZV,NKDPOCZV,DDATPZV,NZVIRKATPR,
                     CNAZPOL2PR,CPLEMENO,MPOPIS,CTYPZVR) 
        SELECT 'S',CNAZPOL1,CNAZPOL4,NZVIRKAT,CNAZPOL2,CNAZEV,NUCETSKUP,CUCETSKUP,CDANPZBO,CTYPSKP,DDATPORKAR,
                     CZKRATJEDN,NKLICDPH,CTYPVYPCEN,CZKRATMENY,NCENANZV,NCENCNZV,NCENAV1ZV,NCENAV2ZV,NCENASZV,NCENACZV,
                     NCENAPZV,NCENAMZV,NMNOZSZV,NKUSYZV,NKD,NCENAPOCZV,NMNOZPOCZV,NKUSYPOCZV,NKDPOCZV,DDATPZV,NZVIRKATPR,
                     CNAZPOL2PR,CPLEMENO,MPOPIS,CTYPZVR
          FROM zvkarobd_ 