INSERT INTO ZVZMENHD (CULOHA,CTYPDOKLAD,CTYPPOHYBU,CDENIK,NROK,NOBDOBI,COBDOBI,NDOKLADUSR,NDOKLAD,NORDITEM,CNAZPOL1,CNAZPOL4,
                      NZVIRKAT,NUCETSKUP,CUCETSKUP,NDRPOHYB,NKARTA,NTYPPOHYB,NDRPOHPRIR,CZKRATJEDN,NKLICDPH,CTYPVYPCEN,
                      NTYPVYPCEL,CZKRATMENY,DDATPORIZ,DDATZMZV,NCISLODL,NCISFAK,CVARSYM,NCENASZV,NKUSYZV,NMNOZSZV,NKD,NKDHLP,
                      NCENACZV,NCENAPZV,NCENAMZV,NCENAPCEZV,NCENAMCEZV,CNAZPOL2,CNAZPOL1_N,CNAZPOL4_N,NZVIRKAT_N,NUCETSKUPN,
                      CUCETSKUPN,CNAZPOL2_N,NCISFIRMY,CUSERABB,DDATZMENY,CCASZMENY,NPORZMENY,NLIKCELDOK,LPRODUKCE,NDRPOHYBP,
                      LZMENAZAKL,CTYPZVR,CFARMA,nKLikvid,nZLikvid)
       SELECT 
                      CULOHA,CTYPDOKLAD,CTYPPOHYBU,CDENIK,NROK,NOBDOBI,COBDOBI,NDOKLADUSR,NDOKLAD,NORDITEM,CNAZPOL1,CNAZPOL4,
                      NZVIRKAT,NUCETSKUP,CUCETSKUP,NDRPOHYB,NKARTA,NTYPPOHYB,NDRPOHPRIR,CZKRATJEDN,NKLICDPH,CTYPVYPCEN,
                      NTYPVYPCEL,CZKRATMENY,DDATPORIZ,DDATZMZV,NCISLODL,NCISFAK,CVARSYM,NCENASZV,NKUSYZV,NMNOZSZV,NKD,NKDHLP,
                      NCENACZV,NCENAPZV,NCENAMZV,NCENAPCEZV,NCENAMCEZV,CNAZPOL2,CNAZPOL1_N,CNAZPOL4_N,NZVIRKAT_N,NUCETSKUPN,
                      CUCETSKUPN,CNAZPOL2_N,NCISFIRMY,CUSERABB,DDATZMENY,CCASZMENY,NPORZMENY,NLIKCELDOK,LPRODUKCE,NDRPOHYBP,
                      LZMENAZAKL,CTYPZVR,CFARMA,nKLikvid,nZLikvid
       FROM ZVZMENHD_  
