delete from maj   ;

insert into MAJ (NINVCIS,NTYPMAJ,CTYPSKP,NODPISK,NTYPDODPI,NTYPUODPI,NROKYODPIU,CNAZEV,NTROBOR,NZNAKT,NDOKLAD,NDRPOHYB,DDATPOR,DDATZAR,COBDZAR,DDATVYRAZ,
COBDVYRAZ,DDATZVYS,COBDZVYS,NROKYDANOD,NROKZVDANO,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NCENAVSTD,NOPRUCT,NOPRDAN,NOPRUCTPS,NOPRDANPS,NPROCDANOD,NDANODPROK,
NPROCUCTOD,NUCTODPROK,NUCTODPMES,NPOCMESUO,NPOCMESDO,NUPLPROC,NUPLHODN,NROKUPL,CKLICODMIS,CKLICSKMIS,CVYRCISIM,DDATREVIM,COBDPOSODP,CNAZPOL1,CNAZPOL2,CNAZPOL3,
CNAZPOL4,CNAZPOL5,CNAZPOL6,MPOPIS,CKODKLAS,CCELEK,CVYKRES,CUMISTENI,CODPISK)
select
NINVCIS,NTYPMAJ,CTYPSKP,NODPISK,NTYPDODPI,NTYPUODPI,NROKYODPIU,CNAZEV,NTROBOR,NZNAKT,NDOKLAD,NDRPOHYB,DDATPOR,DDATZAR,COBDZAR,DDATVYRAZ,
COBDVYRAZ,DDATZVYS,COBDZVYS,NROKYDANOD,NROKZVDANO,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NCENAVSTD,NOPRUCT,NOPRDAN,NOPRUCTPS,NOPRDANPS,NPROCDANOD,NDANODPROK,
NPROCUCTOD,NUCTODPROK,NUCTODPMES,NPOCMESUO,NPOCMESDO,NUPLPROC,NUPLHODN,NROKUPL,CKLICODMIS,CKLICSKMIS,CVYRCISIM,DDATREVIM,COBDPOSODP,CNAZPOL1,CNAZPOL2,CNAZPOL3,
CNAZPOL4,CNAZPOL5,CNAZPOL6,MPOPIS,CKODKLAS,CCELEK,CVYKRES,CUMISTENI,CODPISK
from MAJOBD where cobdobi="02/11" 

delete from majobd  where cobdpoh='02/11'                    ;
delete from zmaju   where cobdobi='03/11'                    ;
delete from ucetpol where cobdobi='03/11' and cdenik='I '    ;
delete from ucetsys where cobdobi='03/11' and culoha='I'    
