delete from majz   ;

insert into MAJZ (NINVCIS,NZVIRKAT,LHMOTNYIM,NUCETSKUP,CUCETSKUP,CTYPSKP,NODPISK,NTYPDODPI,NTYPUODPI,NROKYODPIU,NMESODPIUZ,NTYPVYPUO,CNAZEV,NTROBOR,NZNAKT,NZNAKTD,NDOKLAD,NDRPOHYB,CTYPPOHYBU,DDATPOR,DDATZAR,COBDZAR,DDATVYRAZ,
COBDVYRAZ,DDATZVYS,COBDZVYS,NROKYDANOD,NROKZVDANO,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NCENAVSTD,NOPRUCT,NOPRDAN,NOPRUCTPS,NOPRDANPS,NDOTACEUCT,NDOTACEDAN,NCENAPORU,NCENAPORD,NPROCDANOD,NDANODPROK,
NPROCUCTOD,NUCTODPROK,NUCTODPMES,NPOCMESUO,NPOCMESDO,NUPLPROC,NUPLHODN,NROKUPL,CKLICODMIS,COBDPOSODP,CNAZPOL1,CNAZPOL2,CNAZPOL3,
CNAZPOL4,CNAZPOL5,CNAZPOL6,MPOPIS,NDOKLPREV,CVARSYM,NCISFAK,NZPUODPIS)
select
NINVCIS,NZVIRKAT,LHMOTNYIM,NUCETSKUP,CUCETSKUP,CTYPSKP,NODPISK,NTYPDODPI,NTYPUODPI,NROKYODPIU,NMESODPIUZ,NTYPVYPUO,CNAZEV,NTROBOR,NZNAKT,NZNAKTD,NDOKLAD,NDRPOHYB,CTYPPOHYBU,DDATPOR,DDATZAR,COBDZAR,DDATVYRAZ,
COBDVYRAZ,DDATZVYS,COBDZVYS,NROKYDANOD,NROKZVDANO,NKUSY,NMNOZSTVI,CZKRATJEDN,NCENAVSTU,NCENAVSTD,NOPRUCT,NOPRDAN,NOPRUCTPS,NOPRDANPS,NDOTACEUCT,NDOTACEDAN,NCENAPORU,NCENAPORD,NPROCDANOD,NDANODPROK,
NPROCUCTOD,NUCTODPROK,NUCTODPMES,NPOCMESUO,NPOCMESDO,NUPLPROC,NUPLHODN,NROKUPL,CKLICODMIS,COBDPOSODP,CNAZPOL1,CNAZPOL2,CNAZPOL3,
CNAZPOL4,CNAZPOL5,CNAZPOL6,MPOPIS,NDOKLPREV,CVARSYM,NCISFAK,NZPUODPIS
from MAJOBD where MAJZOBD.cobdpoh='09/12'     ;

delete from majzobd  where cobdpoh='09/12'                    ;
delete from zmajuz   where cobdobi='10/12'                    ;
delete from ucetpol where cobdobi='10/12' and cdenik='Z '    ;
delete from ucetsys where cobdobi='10/12' and culoha='Z'    
