INSERT INTO confighd (CTASK,CITEM,CTYP,CNAME,CVALUE,LRANGE,CPICTURE,DPLATN_OD,DPLATN_DO,NZPUSKONFI,NPRINT,mMETODIKA,CTASKtm,nDistrib,dVznikZazn,dZmenaZazn,mPOZNAMKA,cUniqIdRec,mUserZmenR)
  SELECT CTASK,CITEM,CTYP,CNAME,CVALUE,LRANGE,CPICTURE,DPLATN_OD,DPLATN_DO,NZPUSKONFI,NPRINT,mMETODIKA,CTASKtm,nDistrib,dVznikZazn,dZmenaZazn,mPOZNAMKA,cUniqIdRec,mUserZmenR
   FROM confighd_