INSERT INTO OBJITEM(

  TYPE(FIELD) NAME(nDoklad)    DESC(Èíslo dokladu)                  CAPTION(ÈísloDokl)  FTYPE(n) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(nextObj)    DESC(Externí objednávka)             CAPTION(EXT_obj)    FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nCisFirmy)  DESC(Èíslo firmy)                    CAPTION(ÈísloFirmy) FTYPE(n) FLEN( 5) DEC( 0)
  TYPE(FIELD) NAME(cCinnost)   DESC(Èinnost firmy)                  CAPTION(CinnFirmy)  FTYPE(c) FLEN(15) DEC( 0)
  TYPE(FIELD) NAME(cCislObINT) DESC(Èíslo obj.inter)                CAPTION(ÈísObjInt)  FTYPE(c) FLEN(30) DEC( 0)
  TYPE(FIELD) NAME(nCislPolOb) DESC(Poøadi položek objednávky)      CAPTION(ÈísPolObj)  FTYPE(n) FLEN( 5) DEC( 0)
  TYPE(FIELD) NAME(cNazZBO)    DESC(Název zboží)                    CAPTION(NazZbo)     FTYPE(c) FLEN(50) DEC( 0)
  TYPE(FIELD) NAME(nKlicNaz)   DESC(Klíè názvu zboží)               CAPTION(KlicNazZbo) FTYPE(n) FLEN( 5) DEC( 0)
  TYPE(FIELD) NAME(cSklPol)    DESC(Skladová položka)               CAPTION(SklPoložka) FTYPE(c) FLEN(15) DEC( 0)
  TYPE(FIELD) NAME(cPolCen)    DESC(Ceníková položka A/N)           CAPTION(CenPol)     FTYPE(c) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nZboziKAT)  DESC(Kategorie zboží)                CAPTION(KategZbo)   FTYPE(n) FLEN( 4) DEC( 0)
  TYPE(FIELD) NAME(nKlicDpH)   DESC(Klíè DpH)                       CAPTION(KlicDpH)    FTYPE(n) FLEN( 2) DEC( 0)
  TYPE(FIELD) NAME(NPREDANPOV) DESC(Pøenesená daòová povinnost)     CAPTION(Daò.pov.)   FTYPE(N) FLEN( 1) DEC( 0)  
  TYPE(FIELD) NAME(cCislVpINT) DESC(Èíslo výr.pøíkazu)              CAPTION(cisVyrPrik) FTYPE(c) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(dDatVpINT)  DESC(Datum výr.pøíkazu)              CAPTION(DatVyrPrik) FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(lViceVpINT) DESC(Více výr.pøíkazù)               CAPTION(ViceVyrPri) FTYPE(l) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnozVpINT) DESC(Množství k výrobì)              CAPTION(MnoKVyrobe) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nCenaPrINT) DESC(Cena pøepoètená a rozpoètená)   CAPTION(CenPreARoz) FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(cCisSklad)  DESC(Èíslo skladu)                   CAPTION(ÈísSkladu)  FTYPE(c) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(cCislObDOD) DESC(Èíslo obj.dodavatel)            CAPTION(cisObjDoda) FTYPE(c) FLEN(15) DEC( 0)

* vazba na nabídky vystavené NABVYSIT
  TYPE(FIELD) NAME(ndokladNav)  DESC(Èíslo dokladu nabídky)         CAPTION(DokladNav)  FTYPE(n) FLEN( 5) DEC( 0)
  TYPE(FIELD) NAME(nCisOdes)    DESC(Èíslo nabídky)                 CAPTION(ÈísloNabid) FTYPE(n) FLEN( 5) DEC( 0)
  TYPE(FIELD) NAME(cNazOdes)    DESC(Název nabídky)                 CAPTION(NázevNab)   FTYPE(c) FLEN(15) DEC( 0)
  TYPE(FIELD) NAME(ncountNav)   DESC(Položka nabídky)               CAPTION(PoložkaNav) FTYPE(n) FLEN( 5) DEC( 0)

  TYPE(FIELD) NAME(dDatObDOD)  DESC(Datum obj.dodavatel)            CAPTION(DatObjDod)  FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(nMnozObDOD) DESC(Množství obj.dodavatel)         CAPTION(MnoObjDoda) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nMnozPoDOD) DESC(Množství potvrz.dodav.)         CAPTION(MnoPotvDod) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(dDatPoDOD)  DESC(Datum potvrz.dodav.)            CAPTION(DatPotvDod) FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(nMnozKoDod) DESC(Množství k objedn.dodav.)       CAPTION(MnoKObjDod) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nCenNaoDOD) DESC(Nákupní cena dodav.)            CAPTION(NakCenDod)  FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(nCenProDOD) DESC(Prodejní cena dodav.)           CAPTION(ProdCenDod) FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(dDatPrDOD)  DESC(Datum pøíjmu zboží)             CAPTION(DatPrijZbo) FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(nCenNapDOD) DESC(Nákupní cena pøíjmu)            CAPTION(NakCenPrij) FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(nMnozPrDOD) DESC(Množství pøijato)               CAPTION(MnoPrijato) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nMnozObODB) DESC(Objednáno množství)             CAPTION(ObjMno)     FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nMnozPoODB) DESC(Množství potvrzeno)             CAPTION(MnoPotvrz)  FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nMnozPdODB) DESC(Množství potvrzeno PFa/KSm/EXp) CAPTION(MnoPOTVDok) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(cMnozPoODB) DESC(Množství potvrz.znak)           CAPTION(MnoPotvZna) FTYPE(c) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnozNeODB) DESC(Množství nepotvrzeno)           CAPTION(MnoNepotvr) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(dDatReODB)  DESC(Datum rezervace)                CAPTION(DatRezOdb)  FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(dDatDoOdb)  DESC(Datum doddání zboží)            CAPTION(DatDodaZbo) FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(nMnozReODB) DESC(Množství rezervace)             CAPTION(MnoRezerva) FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nMnozPlODB) DESC(Množství plnìní)                CAPTION(MnoPlneni)  FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nKcsBdObj)  DESC(Celkem bez dane)                CAPTION(CelkBDane)  FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(nKcsZdObj)  DESC(Celkem s dani)                  CAPTION(CelkSDani)  FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(nCenaDlODB) DESC(Prodejní cena na dod.listu)     CAPTION(PrCenDoLis) FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(nIntIndOBJ) DESC(0 nová, 1 oprava, 2 zrušení)    CAPTION(0no1opr2zr) FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(cCisZakaz)  DESC(Èíslo zakázky)                  CAPTION(cisZakazky) FTYPE(c) FLEN(30) DEC( 0)
  TYPE(FIELD) NAME(cCisZakazI) DESC(Èíslo položky výr.zakázky)      CAPTION(polVýrZak)  FTYPE(C) FLEN(36) DEC( 0)
  TYPE(FIELD) NAME(nCislPolZa) DESC(Poøadi položek v zakázce)       CAPTION(ÈísPolZak)  FTYPE(n) FLEN( 5) DEC( 0)
  TYPE(FIELD) NAME(cZkratJedn) DESC(Zkratka mer.jednotky)           CAPTION(ZkrMernJed) FTYPE(c) FLEN( 3) DEC( 0)
  TYPE(FIELD) NAME(nTypSlevy)  DESC(Typ slevy)                      CAPTION(TypSlevy)   FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nProcSlev)  DESC(Procento slevy)                 CAPTION(ProcSlevy)  FTYPE(n) FLEN( 7) DEC( 4)
  TYPE(FIELD) NAME(nPROCslFAO) DESC(Procento slevy FAO)             CAPTION(ProSlevFaO) FTYPE(n) FLEN( 7) DEC( 4)
  TYPE(FIELD) NAME(lPROCslFAO) DESC(Procento slevy FAO z HD)        CAPTION(ProSlevFA)  FTYPE(l) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nPROCslHOT) DESC(Procento slevy HOT)             CAPTION(ProcSlHOT)  FTYPE(n) FLEN( 7) DEC( 4)
  TYPE(FIELD) NAME(nPROCslMNO) DESC(Procento slemy MNO)             CAPTION(ProcSlMNO)  FTYPE(n) FLEN( 7) DEC( 4)
  TYPE(FIELD) NAME(nHodnSlev)  DESC(Hodnota slevy)                  CAPTION(HodnSlevy)  FTYPE(n) FLEN(13) DEC( 4)
  TYPE(FIELD) NAME(nCenaZakl)  DESC(Cena základní bez slevy)        CAPTION(CenZakBSle) FTYPE(n) FLEN(13) DEC( 2)
  TYPE(FIELD) NAME(nCelkSlev)  DESC(Celkem sleva)                   CAPTION(CelkSleva)  FTYPE(n) FLEN(13) DEC( 4)
  TYPE(FIELD) NAME(nKlicObl)   DESC(Klíè oblasti)                   CAPTION(KlicOblast) FTYPE(n) FLEN( 3) DEC( 0)
  TYPE(FIELD) NAME(cZkrProdej) DESC(Zkratka prodejce)               CAPTION(ZkrProdej)  FTYPE(c) FLEN( 4) DEC( 0)
  TYPE(FIELD) NAME(nPodilProd) DESC(Podíl prodejce)                 CAPTION(PodílProd)  FTYPE(n) FLEN( 6) DEC( 2)
  TYPE(FIELD) NAME(nMnPotVyr)  DESC(Mn.potvrzené výrobou)           CAPTION()           FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nMnPusVyr)  DESC(Mn. puštìné do výroby)          CAPTION()           FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(dPusVyr)    DESC(Dat.puštìní do výroby)          CAPTION()           FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(nMnPriVyr)  DESC(Mn. pøijato z výroby)           CAPTION()           FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(dPriVyr)    DESC(Dat.pøijetí z výroby)           CAPTION()           FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(cVyrPol)    DESC(Vyrábìná položka)               CAPTION()           FTYPE(c) FLEN(15) DEC( 0)
  TYPE(FIELD) NAME(nVarCis)    DESC(Varianta vyr.položky)           CAPTION()           FTYPE(n) FLEN( 3) DEC( 0)
  TYPE(FIELD) NAME(cStred)     DESC(Støedisko požadující)           CAPTION()           FTYPE(c) FLEN( 8) DEC( 0) RELATETO(c_Stred) RELATETYPE(2)
  TYPE(FIELD) NAME(nRAvyska)   DESC(Výška)                          CAPTION()           FTYPE(n) FLEN(11) DEC( 3)
  TYPE(FIELD) NAME(nRBsirka)   DESC(Šíøka)                          CAPTION()           FTYPE(n) FLEN(11) DEC( 3)
  TYPE(FIELD) NAME(lPozVyroba) DESC(Požadavek z výroby)             CAPTION()           FTYPE(l) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnKalkul)  DESC(Kalkulaèní množství)            CAPTION()           FTYPE(n) FLEN(10) DEC( 2)
  TYPE(FIELD) NAME(nDelka)     DESC(Délka)                          CAPTION()           FTYPE(n) FLEN( 5) DEC( 2)
  TYPE(FIELD) NAME(nPocet)     DESC(Poèet)                          CAPTION()           FTYPE(n) FLEN( 9) DEC( 2)
  TYPE(FIELD) NAME(nPozice)    DESC(Pozice)                         CAPTION()           FTYPE(n) FLEN( 3) DEC( 0)
  TYPE(FIELD) NAME(nMnNaKus)   DESC(Množství na kus)                CAPTION()           FTYPE(n) FLEN(10) DEC( 3)
  TYPE(FIELD) NAME(cText1)     DESC(Text 1)                         CAPTION()           FTYPE(c) FLEN(30) DEC( 0)
  TYPE(FIELD) NAME(cText2)     DESC(Text 2)                         CAPTION()           FTYPE(c) FLEN(30) DEC( 0)
  TYPE(FIELD) NAME(nRokRV)     DESC(Rok)                            CAPTION(RokVytvoø)  FTYPE(N) FLEN( 4) DEC( 0)
  TYPE(FIELD) NAME(nPolObjRV)  DESC(ID objednávky)                  CAPTION(ID_objedn.) FTYPE(n) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(dDATodvVYR) DESC(Datum odvedení z výroby)        CAPTION(DATodvVYR)  FTYPE(D) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(cPOPpolOBJ) DESC(Popis položky OBJ_pøijaté)      CAPTION(POPpolOBJ)  FTYPE(C) FLEN(30) DEC( 0)
  TYPE(FIELD) NAME(nUCETskup)  DESC(Úèetní skup.)                   CAPTION(ÚèetníSkup) FTYPE(N) FLEN( 3) DEC( 0)
  TYPE(FIELD) NAME(aULOZENI)   DESC()                               CAPTION()           FTYPE(M) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(dRezerv)    DESC(Pøerezervace KDY)               CAPTION()           FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(cRezerv)    DESC(Pøerezervace KDO)               CAPTION()           FTYPE(c) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(nNavysPRC)  DESC(% navýšení)                     CAPTION()           FTYPE(n) FLEN( 5) DEC( 2)
  TYPE(FIELD) NAME(nKusRoz)    DESC(Kusy daných rozmìrù)            CAPTION()           FTYPE(n) FLEN( 7) DEC( 3)
  TYPE(FIELD) NAME(nCisOper)   DESC(Èís. operace)                   CAPTION()           FTYPE(n) FLEN( 4) DEC( 0)
  TYPE(FIELD) NAME(nPocCeZapZ) DESC(Poèet zapuštìní)                CAPTION()           FTYPE(n) FLEN( 2) DEC( 0)
  TYPE(FIELD) NAME(cKodPoz)    DESC(Kód pozice)                     CAPTION()           FTYPE(c) FLEN( 3) DEC( 0)
  TYPE(FIELD) NAME(ccistrasyp) DESC(Èíslo trasy_pl)                 CAPTION(cisTrasy_p) FTYPE(c) FLEN(10) DEC( 0) RELATETO(C_TRASY) RELATETYPE(2)
  TYPE(FIELD) NAME(ccistrasys) DESC(Èíslo trasy_sk)                 CAPTION(cisTrasy_s) FTYPE(c) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(nCisDodavk) DESC(Èíslo dodávky)                  CAPTION(ÈísDodávky) FTYPE(n) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(NMNOZSZBO)  DESC(Množství na skladu)             CAPTION(MnSkladem)  FTYPE(N) FLEN(11) DEC( 2)
  TYPE(FIELD) NAME(NMNOZKZBO)  DESC(Množství k objednání)           CAPTION(MnKObjend)  FTYPE(N) FLEN(11) DEC( 2)
  TYPE(FIELD) NAME(NMNOZOZBO)  DESC(Objednané množství)             CAPTION(MnObjedn)   FTYPE(N) FLEN(11) DEC( 2)
  TYPE(FIELD) NAME(NMNOZRZBO)  DESC(Rezervované množství)           CAPTION(MnRezerv)   FTYPE(N) FLEN(11) DEC( 2)
  TYPE(FIELD) NAME(NMNOZDZBO)  DESC(Množství k dispozici)           CAPTION(MnKDisp)    FTYPE(N) FLEN(11) DEC( 2)
*
  TYPE(FIELD) NAME(nCisVysFak) DESC(Èís. vyst.faktury odbìratele)   CAPTION(ÈísloFakt)  FTYPE(n) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(cDoplnTxt)  DESC(Doplòující text)                CAPTION(DoplText)   FTYPE(c) FLEN(50) DEC( 0)
*
  TYPE(FIELD) NAME(nMnoz_FAKT) DESC(Množství fakturované)           CAPTION(MnožFakt)      FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nstav_FAKT) DESC(Stav fakturace)                 CAPTION(MnožFakt)      FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_DLVY) DESC(Množství vydané)                CAPTION(MnožDod)       FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nMnoz_OBJP) DESC(Množství vykryté)               CAPTION(MnožVykryt)    FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nMnoz_EXPL) DESC(Množství vyexpedované)          CAPTION(MnožVyexp)     FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nMnoz_ZAK)  DESC(Množství vykryté na zak)        CAPTION(MnožVykrytZak) FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(ddatRvykr)  DESC(Datum ruèního vykrytí)          CAPTION(datRvykr)      FTYPE(D) FLEN( 8) DEC( 0)
*
  TYPE(FIELD) NAME(NHMOTNOSTJ) DESC(Hmotnost_jedn)                  CAPTION(HmotnostJed)   FTYPE(N) FLEN(15) DEC(4)
  TYPE(FIELD) NAME(NOBJEMJ)    DESC(Objem_jedn)                     CAPTION(ObjemJed)      FTYPE(N) FLEN(15) DEC(4)
  TYPE(FIELD) NAME(NHMOTNOST)  DESC(Hmotnost)                       CAPTION(Hmotnost)      FTYPE(N) FLEN(15) DEC(4)
  TYPE(FIELD) NAME(NOBJEM)     DESC(Objem)                          CAPTION(Objem)         FTYPE(N) FLEN(15) DEC(4)

* vykrývání obchodního pøípadu  
  TYPE(FIELD) NAME(nMnoz_NABV) DESC(Množství vykryté nab.vys.)      CAPTION(MnožVyNabV)     FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_NABV) DESC(Stav vykrytí NABV)              CAPTION(StavVyNabV)     FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_FAKV) DESC(Množství vykryté fakt.vys.)     CAPTION(MnožVyFaktV)    FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_FAKV) DESC(Stav vykrytí FAKT)              CAPTION(StavVyFaktV)    FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_DLV)  DESC(Množství vykryté dod.list.)     CAPTION(MnožVyDodLV)    FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_DLV)  DESC(Stav vykrytí DLV)               CAPTION(StavVyDodLV)    FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_OBJP) DESC(Množství vykryté obj.pøij.)     CAPTION(MnožVyObjPø)    FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_OBJP) DESC(Stav vykrytí OBJP)              CAPTION(StavVyObjPø)    FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_EXLV) DESC(Množství vykryté exped.list.)   CAPTION(MnožVyExLiVy)   FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_EXLV) DESC(Stav vykrytí EXLV)              CAPTION(StavVyExLiVy)   FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_VYRZ) DESC(Množství vykryté výr.zak.)      CAPTION(MnožVyVyrZak)   FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_VYRZ) DESC(Stav vykrytí VYRZ)              CAPTION(StavVyVyrZak)   FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_KSMV) DESC(Množství vykryté kup.sml.vys)   CAPTION(MnožVyKSmV)     FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_KSMV) DESC(Stav vykrytí KSMV)              CAPTION(StavVyKSmV)     FTYPE(n) FLEN( 1) DEC( 0)
  TYPE(FIELD) NAME(nMnoz_SVYD) DESC(Množství vykryté sklad.vyd.)    CAPTION(MnožVySVyd)     FTYPE(n) FLEN(15) DEC( 4)
  TYPE(FIELD) NAME(nStav_SVYD) DESC(Stav vykrytí SVYD)              CAPTION(StavVySVyd)     FTYPE(n) FLEN( 1) DEC( 0)
*
  TYPE(FIELD) NAME(nMnozZdok)  DESC(Množství z dokladu)             CAPTION(MnozZdok)      FTYPE(n) FLEN(15) DEC( 4)
*
  TYPE(FIELD) NAME(dVznikZazn)  DESC(Datum vzniku)                CAPTION(DatVzniku)     FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(dZmenaZazn)  DESC(Datum zmìny)                 CAPTION(DatVzniku)     FTYPE(d) FLEN( 8) DEC( 0)
  TYPE(FIELD) NAME(mPoznamka)   DESC(Poznámka)                    CAPTION(Poznámka)      FTYPE(m) FLEN(10) DEC( 0)
  TYPE(FIELD) NAME(mUserZmenR)  DESC()                            CAPTION()              FTYPE(m) FLEN(10) DEC( 0)




CULOHA,CTASK,CSUBTASK,CTYPDOKLAD,CTYPPOHYBU,nTypPVP,NDOKLAD,CCISSKLAD,CSKLPOL,CPOLCEN,NORDITEM,NUCETSKUP,CUCETSKUP,DDATPVP,CCASPVP,COBDPOH,NROK,NOBDOBI,NTYPPOH,    
NCISLPOH,NKLICNAZ,CNAZZBO,NZBOZIKAT,NKLICNS,NCENNAPDOD,NCENADOKL1,NMNOZDOKL1,CMJDOKL1,NMNOZPRDOD,NCENACELK,NCENAPZBO,NCENAPDZBO,NKLICDPH,CZKRATJEDN,CZKRATMENY,NMNOZSZBO,NCENACZBO,CCISOBJ,NINTCOUNT,CCISLOBINT,NCISLPOLOB,NMNOZPOODB,NMNOZREODB,NMNOZVYOBJ,NMNOZKOBJE,NMNOZZOBJE,NMNOZVYOBV,NMNOZVPINT,NCISLOPVP,NCISFAK,NCISLODL,CSKLADKAM,CSKLPOLKAM,NORDITKAM,NUCETSKKAM,CUCETSKKAM,NDOKLADV,CUCTOVANO,CNAZPOL1,CNAZPOL2,CNAZPOL3,CNAZPOL4,CNAZPOL5,CNAZPOL6,NTYPSLEVY,NPROCSLEV,NPROCSLFAO,NPROCSLMN,NHODNSLEV,NCELKSLEV,NCENAZAKL,LOGAMOPREN,CZKRPRODEJ,NPODILPROD,CDENIK,CCISZAKAZ,cCisZakazI,CVYRPOL,NVARCIS,CKODTPV,NKLICOBL,CZAHRMENA,NCENNADOZM,NCENCELKZM,CKLICODMIS,NINVCISDIM,AULOZENI,CTYPSKP,NKOEFMN,NMNOZPRKOE,NCEJPRZBZ,NCEJPRKBZ,NCEJPRKDZ,NCECPRZBZ,NCECPRKBZ,NCECPRKDZ,NHMOTNOST,NOBJEM,COBDOBI,nKLikvid,nZLikvid,nRozdilPoh,NCISFIRMY,CTEXT,NUSRIDDBTE,dVznikZazn,dZmenaZazn,mUserZmenR,cUniqIdRec) SELECT CULOHA,CTASK,CSUBTASK,CTYPDOKLAD,CTYPPOHYBU,nTypPVP,NDOKLAD,CCISSKLAD,CSKLPOL,CPOLCEN,NORDITEM,NUCETSKUP,CUCETSKUP,DDATPVP,CCASPVP,COBDPOH,NROK,NOBDOBI,NTYPPOH,    
NCISLPOH,NKLICNAZ,CNAZZBO,NZBOZIKAT,NKLICNS,NCENNAPDOD,NCENADOKL1,NMNOZDOKL1,CMJDOKL1,NMNOZPRDOD,NCENACELK,NCENAPZBO,NCENAPDZBO,NKLICDPH,CZKRATJEDN,CZKRATMENY,NMNOZSZBO,NCENACZBO,CCISOBJ,NINTCOUNT,CCISLOBINT,NCISLPOLOB,NMNOZPOODB,NMNOZREODB,NMNOZVYOBJ,NMNOZKOBJE,NMNOZZOBJE,NMNOZVYOBV,NMNOZVPINT,NCISLOPVP,NCISFAK,NCISLODL,CSKLADKAM,CSKLPOLKAM,NORDITKAM,NUCETSKKAM,CUCETSKKAM,NDOKLADV,CUCTOVANO,CNAZPOL1,CNAZPOL2,CNAZPOL3,CNAZPOL4,CNAZPOL5,CNAZPOL6,NTYPSLEVY,NPROCSLEV,NPROCSLFAO,NPROCSLMN,NHODNSLEV,NCELKSLEV,NCENAZAKL,LOGAMOPREN,CZKRPRODEJ,NPODILPROD,CDENIK,CCISZAKAZ,cCisZakazI,CVYRPOL,NVARCIS,CKODTPV,NKLICOBL,CZAHRMENA,NCENNADOZM,NCENCELKZM,CKLICODMIS,NINVCISDIM,AULOZENI,CTYPSKP,NKOEFMN,NMNOZPRKOE,NCEJPRZBZ,NCEJPRKBZ,NCEJPRKDZ,NCECPRZBZ,NCECPRKBZ,NCECPRKDZ,NHMOTNOST,NOBJEM,COBDOBI,nKLikvid,nZLikvid,nRozdilPoh,NCISFIRMY,CTEXT,NUSRIDDBTE,dVznikZazn,dZmenaZazn,mUserZmenR,cUniqIdRec FROM PVPITEM_
