INSERT INTO c_typpoh (CULOHA,CPODULOHA,CTYPDOKLAD,CTYPPOHYBU,CSUBPOHYB,CNAZTYPPOH,CRADDPH,CRADDPH091,CTASK,CSUBTASK,
CTYPKURZU,lNaklStr,mPOPITYPPO,DPLATNYOD,DPLATNYDO,NKARTA,LPRODUKCE,NTYPPOHYB,NDRPOHPL1,NDRPOHPL2,NDRPOHPLPR,
NPODM,nDistrib,dVznikZazn,dZmenaZazn,mPOZNAMKA,cUniqIdRec,mUserZmenR ) SELECT CULOHA,CPODULOHA,CTYPDOKLAD,CTYPPOHYBU,CSUBPOHYB,CNAZTYPPOH,CRADDPH,CRADDPH091,CTASK,CSUBTASK,
CTYPKURZU,lNaklStr,mPOPITYPPO,DPLATNYOD,DPLATNYDO,NKARTA,LPRODUKCE,NTYPPOHYB,NDRPOHPL1,NDRPOHPL2,NDRPOHPLPR,
NPODM,nDistrib,dVznikZazn,dZmenaZazn,mPOZNAMKA,cUniqIdRec,mUserZmenR FROM c_typpoh_