INSERT INTO cenprodc (  
             NKLICCENZB,CCISSKLAD,CSKLPOL,NZBOZIKAT,CNAZZBO,NCENCNZBO,NCENAPZBO,NCENAMZBO,NPROCMARZ,NCENAP1ZBO,NPROCMARZ1,NCENAP2ZBO,NPROCMARZ2,
             NCENAP3ZBO,NPROCMARZ3,NCENAP4ZBO,NPROCMARZ4,DDATAKT)
       SELECT 
             NKLICCENZB,CCISSKLAD,CSKLPOL,NZBOZIKAT,CNAZZBO,NCENCNZBO,NCENAPZBO,NCENAMZBO,NPROCMARZ,NCENAP1ZBO,NPROCMARZ1,NCENAP2ZBO,NPROCMARZ2,
             NCENAP3ZBO,NPROCMARZ3,NCENAP4ZBO,NPROCMARZ4,DDATAKT
          FROM cenprodc_