INSERT INTO forms (CTYPFORMS,NCISFORMS,CFORMNAME,CIDFORMS,CIDFILTERS,LISFORM,NTYPPROJ_L,NTYPPRINT,
                        NTYPZPR,CUSER,CGROUP,CTASK,CMAINFILE,MFORMS_LL,NFORMS_LL,MDATA_LL,MTISK_LL,MBLOCKFRM,
                        MBLOC_USER,nVER_MAJOR,nVER_MINOR,
                        mMETODIKA,nDistrib,dVznikZazn,dZmenaZazn,mPOZNAMKA,mUserZmenR)
        SELECT CTYPFORMS,NCISFORMS,CFORMNAME,CIDFORMS,CIDFILTERS,LISFORM,NTYPPROJ_L,NTYPPRINT,
                        NTYPZPR,CUSER,CGROUP,CTASK,CMAINFILE,MFORMS_LL,NFORMS_LL,MDATA_LL,MTISK_LL,MBLOCKFRM,
                        MBLOC_USER,nVER_MAJOR,nVER_MINOR,
                        mMETODIKA,nDistrib,dVznikZazn,dZmenaZazn,mPOZNAMKA,mUserZmenR
             FROM forms_
 