INSERT INTO c_danskp (CODPISKD,NODPISKD,CODPISK,NODPISK,LHMOTNYIM,CMJCAS,NMESODPID,NROKYODPIS,NMESTZHOD,NROPRVNI,NRODALSI,NROZVCENA,NZRPRVNI,
                       NZRDALSI,NZRZVCENA,NROPRVNI10,NRODALSI10,NROZVCEN10,NROPRVNI15,NRODALSI15,NROZVCEN15,NROPRVNI20,NRODALSI20,NROZVCEN20, 
                        mMETODIKA,nDistrib,dVznikZazn,dZmenaZazn,mPoznamka,cUniqIdRec,mUserZmenR)
        SELECT CODPISKD,NODPISKD,CODPISK,NODPISK,LHMOTNYIM,CMJCAS,NMESODPID,NROKYODPIS,NMESTZHOD,NROPRVNI,NRODALSI,NROZVCENA,NZRPRVNI,
                       NZRDALSI,NZRZVCENA,NROPRVNI10,NRODALSI10,NROZVCEN10,NROPRVNI15,NRODALSI15,NROZVCEN15,NROPRVNI20,NRODALSI20,NROZVCEN20, 
                        mMETODIKA,nDistrib,dVznikZazn,dZmenaZazn,mPoznamka,cUniqIdRec,mUserZmenR
          FROM c_danskp_