INSERT INTO cenzboz ( 
  CCISSKLAD,CSKLPOL,NKLICNAZ,NZBOZIKAT,CZBOPODKAT,NUCETSKUP,CUCETSKUP,CNAZZBO,CNAZZBO2,CTYPSKLPOL,CKATCZBO,CJKPOV,CDANPZBO,CZKRATJEDN,NKLICDPH,
  nNAPOCET,NCENANZBO,NCENCNZBO,NCENAKURZ,CZKRATMENY,CZAHRMENA,NCENAPZBO,NCENAMZBO,NCENASZBO,NCENACZBO,NCENASVZM,NCENAVNI,NCENAPOC,NMNOZPOC,
  NMNOZSZBO,NMNOZKZBO,NMNOZOZBO,NMNOZRZBO,NMNOZRSES,NMNOZDZBO,NMNOZNZBO,NMAXZBO,NMINZBO,DDATPZBO,NRECNAB,NRECZBO,CZKRCARKOD,NCARKKOD,NTYPGENBCD,
  cCarKod,NCENPOL,CBAL,NBALKS,CCENSES,NPRISRAZBO,lMistaUloz,CULOZZBO,CULOZSYS,LVICECENP,CTYPSKLCEN,CPOLCEN,CVYRCIS,CKATALCIS,CVYROBCE,CJAKOST,
  CZKRMAT,MPOZZBO,NULOZCELK,CTYPSKP,cTypCZCPA,NKOEFMN,NPRIRAZKA,NHMOTNOST,CZKRATJEDH,NOBJEM,CZKRATJEDO,NNADMNOZzD,LAKTIVNI,NPREDANPOV,nTypPreDan,
  NMNOZWORK)
        SELECT 
  CCISSKLAD,CSKLPOL,NKLICNAZ,NZBOZIKAT,CZBOPODKAT,NUCETSKUP,CUCETSKUP,CNAZZBO,CNAZZBO2,CTYPSKLPOL,CKATCZBO,CJKPOV,CDANPZBO,CZKRATJEDN,NKLICDPH,
  nNAPOCET,NCENANZBO,NCENCNZBO,NCENAKURZ,CZKRATMENY,CZAHRMENA,NCENAPZBO,NCENAMZBO,NCENASZBO,NCENACZBO,NCENASVZM,NCENAVNI,NCENAPOC,NMNOZPOC,
  NMNOZSZBO,NMNOZKZBO,NMNOZOZBO,NMNOZRZBO,NMNOZRSES,NMNOZDZBO,NMNOZNZBO,NMAXZBO,NMINZBO,DDATPZBO,NRECNAB,NRECZBO,CZKRCARKOD,NCARKKOD,NTYPGENBCD,
  cCarKod,NCENPOL,CBAL,NBALKS,CCENSES,NPRISRAZBO,lMistaUloz,CULOZZBO,CULOZSYS,LVICECENP,CTYPSKLCEN,CPOLCEN,CVYRCIS,CKATALCIS,CVYROBCE,CJAKOST,
  CZKRMAT,MPOZZBO,NULOZCELK,CTYPSKP,cTypCZCPA,NKOEFMN,NPRIRAZKA,NHMOTNOST,CZKRATJEDH,NOBJEM,CZKRATJEDO,NNADMNOZzD,LAKTIVNI,NPREDANPOV,nTypPreDan,
  NMNOZWORK
          FROM cenzboz_