INSERT INTO mzdzavhd (cUloha,CTYPDOKLAD,CTYPPOHYBU,nhasItems,dPorizFak,cObdobi,nROK,nOBDOBI,cObdobiDan,nCisFak,cVarSym,cdanDoklad,
                      cZkrTypFak,cZkrTypUhr,nTypZav,cTextFakt,nKlicDPH,nOsvOdDan,nPROCdan_1,nZaklDan_1,nSazDan_1,nZAKLdaz_1,
                      nSAZdaz_1,nPROCdan_2,nZaklDan_2,nSazDan_2,nZAKLdaz_2,nSAZdaz_2,nPROCdan_3,nZaklDan_3,nSazDan_3,nZAKLdaz_3,nSAZdaz_3,
                      nSUMAdan,nCenZakCel,nCENfakCEL,nCENfazCEL,nZustPoZao,nKodZaokr,nKodZaokrD,cZkratMeny,nCenZahCel,cZkratMenZ,
                      nKurZahMen,nMnozPrep,nKurZahMeD,nMnozPreD,nKonstSymb,cSpecSymb,nCisFirmy,cNazev,cNazev2,nIco,cDic,cUlice,
                      cCisPopis,cCisOrien,cUlicCisla,cObec,cSidlo,cPsc,cZkratStat,cUcet,dVystFAKDo,dSplatFak,dVystFak,dDatTisk,
                      nExiPriUhr,nPriUhrCel,dDatPriUhr,nUhrCelFak,nUhrCelFaZ,nKurzROZDf,dPosUhrFak,nPARzalFAK,nPARzahFAK,dPARzalFAK,
                      cBank_Uct,cVnBan_Uct,nCisDobFak,dPosLikFak,cPrizLikv,nLikCelFak,nCisUzv,dDatUzv,cDenik,cUcet_Uct,cDENIK_puc,
                      cUCET_pucR,cUCET_pucS,cUCET_daz,cCisObj,cJmenoPrev,dDatPrevz,dDatVratil,cZkrProdej,lDovoz,nDOKLAD_DR,nCelZakl_1,
                      nCelClo_1,nCelSPD_1,nCELDAL_1,nCelZakl_2,nCelClo_2,nCelSPD_2,nCELDAL_2,nCelZakl_3,nCelClo_3,nCelSPD_3,nCELDAL_3,
                      nHmotnost,cZkratJedH,nObjem,cZkratJedO,nFinTyp,nDoklad,nNULLdph,cINT_ozn,mPopisFAK,lNo_InDPH,cIsZAL_FAK,
                      nKLikvid,nZLikvid,TRVZAVHD,dVznikZazn,dZmenaZazn,mPoznamka,nRokObd,nOsCisPrac,nPorPraVzt,nCisOsoby,nDruhMzdy,
                      nZdrPojis,nMZDYIT)  
             SELECT   cUloha,CTYPDOKLAD,CTYPPOHYBU,nhasItems,dPorizFak,cObdobi,nROK,nOBDOBI,cObdobiDan,nCisFak,cVarSym,cdanDoklad,
                      cZkrTypFak,cZkrTypUhr,nTypZav,cTextFakt,nKlicDPH,nOsvOdDan,nPROCdan_1,nZaklDan_1,nSazDan_1,nZAKLdaz_1,
                      nSAZdaz_1,nPROCdan_2,nZaklDan_2,nSazDan_2,nZAKLdaz_2,nSAZdaz_2,nPROCdan_3,nZaklDan_3,nSazDan_3,nZAKLdaz_3,nSAZdaz_3,
                      nSUMAdan,nCenZakCel,nCENfakCEL,nCENfazCEL,nZustPoZao,nKodZaokr,nKodZaokrD,cZkratMeny,nCenZahCel,cZkratMenZ,
                      nKurZahMen,nMnozPrep,nKurZahMeD,nMnozPreD,nKonstSymb,cSpecSymb,nCisFirmy,cNazev,cNazev2,nIco,cDic,cUlice,
                      cCisPopis,cCisOrien,cUlicCisla,cObec,cSidlo,cPsc,cZkratStat,cUcet,dVystFAKDo,dSplatFak,dVystFak,dDatTisk,
                      nExiPriUhr,nPriUhrCel,dDatPriUhr,nUhrCelFak,nUhrCelFaZ,nKurzROZDf,dPosUhrFak,nPARzalFAK,nPARzahFAK,dPARzalFAK,
                      cBank_Uct,cVnBan_Uct,nCisDobFak,dPosLikFak,cPrizLikv,nLikCelFak,nCisUzv,dDatUzv,cDenik,cUcet_Uct,cDENIK_puc,
                      cUCET_pucR,cUCET_pucS,cUCET_daz,cCisObj,cJmenoPrev,dDatPrevz,dDatVratil,cZkrProdej,lDovoz,nDOKLAD_DR,nCelZakl_1,
                      nCelClo_1,nCelSPD_1,nCELDAL_1,nCelZakl_2,nCelClo_2,nCelSPD_2,nCELDAL_2,nCelZakl_3,nCelClo_3,nCelSPD_3,nCELDAL_3,
                      nHmotnost,cZkratJedH,nObjem,cZkratJedO,nFinTyp,nDoklad,nNULLdph,cINT_ozn,mPopisFAK,lNo_InDPH,cIsZAL_FAK,
                      nKLikvid,nZLikvid,TRVZAVHD,dVznikZazn,dZmenaZazn,mPoznamka,nRokObd,nOsCisPrac,nPorPraVzt,nCisOsoby,nDruhMzdy,
                      nZdrPojis,nMZDYIT
               FROM mzdzavhd_ 
