INSERT INTO frmusers (CFORMNAME,CUSER,CCALLFORM,CIDFORMS,CIDFILTERS,MTISK,dVznikZazn,dZmenaZazn,mPOZNAMKA,mUserZmenR)
        SELECT CFORMNAME,'gonsenjana',CCALLFORM,CIDFORMS,CIDFILTERS,MTISK,dVznikZazn,dZmenaZazn,mPOZNAMKA,mUserZmenR
             FROM frmusers_